### ISSUE TITLE
Test runner fails on hello-world

### ISSUE THREAD

**Issue by BNAndras** [exercism/gdscript-test-runner#12]
@exercism/gdscript

My hello-world solution fails even though all I did was replace the text between the double quotes.

```gdscript
func hello():
	return "Hello, World!"
```

![image](https://github.com/exercism/gdscript-test-runner/assets/20251272/2306447b-3362-46cb-8043-d427e9fafffe)

**Comment by ErikSchierboom** [comment]
@BNAndras That's because we don't yet deploy the test runner to production. Will be fixed on https://github.com/exercism/terraform/pull/107 is merged and the terraform scripts are run.

**Comment by BNAndras** [comment]
Test runner runs successfully now.
